apiVersion: v1
kind: Pod
metadata: 
  name: app-kuber-2
  labels:
    enviroment: dev
    app: http-server
spec:
  containers:
  - name: app-kuber-container
    image: nginx:latest
    ports:
    - containerPort: 80
