apiVersion: v1 #версия API 
kind: Pod #какой объект описываем
namespace: test #указываем пространство имен
metadata:   #дополнительные данные поду
  name: app-kuber-2 #имя пода
  labels:           #метки для пода 
    enviroment: dev   #метка
    app: http-server  #метка
spec: #спецификация
  nodeSelector: #указываем метку ноды на которой должен запускаться под
    gpu: "true" #описание самой метки
  containers:   #описание контейнера 
  - name: app-kuber-container #имя контейнера
    image: nginx:latest #образ контейнера
    ports:  #открываем порта 
    - containerPort: 80 #указываем порты 
