apiVersion: apps/v1  # Версия API для создания объектов ReplicaSet.
kind: ReplicaSet  # Тип объекта, который мы создаем - ReplicaSet.
metadata:
  name: kuber-rs-1  # Имя ReplicaSet.
  labels:
    app: kuber-rs  # Метка, присвоенная ReplicaSet.
spec:
  replicas: 3  # Желаемое количество реплик (подов).
  selector:
    matchLabels:
      env: dev  # Селектор, который выбирает поды с меткой "env: dev".
  template:  # Шаблон для создания подов, управляемых ReplicaSet.
    metadata:
      labels:
        env: dev  # Метка, присвоенная подам, созданным из этого шаблона.
    spec:
      containers:
      - name: kuber-app  # Имя контейнера.
        image: bokovets/kuber  # Образ контейнера для запуска в поде.
